# Generated by Django 5.2 on 2025-05-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_recipe_image_alter_recipe_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='contect1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contect', models.IntegerField(blank=True, null=True)),
                ('massage', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe'),
        ),
    ]
