# Generated by Django 5.2 on 2025-06-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contect1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contect', models.IntegerField(blank=True, null=True)),
                ('massage', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
