# Generated by Django 5.2 on 2025-06-11 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('henishapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contect1',
            name='contect',
        ),
    ]
