# Generated by Django 5.2 on 2025-06-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('henishapp', '0002_remove_contect1_contect'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contect1',
            new_name='contect_now',
        ),
    ]
