# Generated by Django 5.2 on 2025-06-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amd_name', models.CharField(max_length=20)),
                ('amd_password', models.CharField(max_length=20)),
                ('amd_email', models.EmailField(max_length=20)),
                ('amd_status', models.BooleanField(max_length=20)),
            ],
        ),
    ]
