# Generated by Django 5.2 on 2025-06-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='catagoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=100)),
                ('catImage', models.ImageField(upload_to='catagory_images')),
                ('catStatus', models.BooleanField(default=True)),
                ('catSlug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='admin_user',
            name='amd_password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='admin_user',
            name='amd_status',
            field=models.BooleanField(default=True),
        ),
    ]
