# Generated by Django 5.2 on 2025-06-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_catagorymaster_alter_admin_user_amd_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catagoryMaster',
            new_name='categoryMaster',
        ),
    ]
